### ISSUE TITLE
Publish to github.io

### ISSUE THREAD

**Issue by mrdoob** [Achifaifa/urlol#1]
How about renaming `urlol` to `index.html` and creating a `gh-pages` branch?
That way the demo will be available at http://Achifaifa.github.io/urlol/

**Comment by Achifaifa** [comment]
There's already a live version [here](http://achi.se/projects/software/urlol), i sent requests to update the info in the pouet page but it's not there yet :)

**Comment by mrdoob** [comment]
I see...
